### ISSUE TITLE
Test all the CRUD Operations

### ISSUE THREAD

**Issue by atapas** [atapas/vento#23]
Test out all the CRUD Operations

**Comment by DhyaniKanika** [comment]
The compiled test results can be found [here](https://github.com/atapas/vento/wiki/CRUD-operations)
The following bugs were found
[Deleting multiple records at once in asset-consumer-map](https://github.com/atapas/vento/issues/28)
[Deleting multiple records at once in asset-notification-map](https://github.com/atapas/vento/issues/27)
[Adding new records to Asset-notification-map](https://github.com/atapas/vento/issues/25)

And a functionality to [Add multiple records](https://github.com/atapas/vento/issues/26) at once is requested.

I will be closing this issue now.
